### ISSUE TITLE
Crear Categorias

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#1]
Vamos a crear un modelo de categorias con los siguientes campos

category

user_id: integer
name: string
available: boolean

Correr e siguiente comando

rails generate scaffold Category user_id:integer name:string available:boolean

Agregar tambien las relaciones a los respectivos modelos
has_many: categories  en user
belongs_to: user en category

Crear un branch que se llame -> categories

**Comment by kamirob** [comment]
Se crearon las categorías utilizando scaffold

**Comment by DanielArenas** [comment]
No puedo ver el check Available en categorias

![screen shot 2017-10-19 at 7 17 12 am](https://user-images.githubusercontent.com/22307128/31770467-a5e7db92-b49d-11e7-8525-205e5daae77f.png)

**Comment by kamirob** [comment]
Se actualizaron los estilos del formulario New Category, ya se ve el checkbox.
