### ISSUE TITLE
Model credit card

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#10]
Agregar pantalla para agregar las credit card

campos:
Nombre -> string
flag -> enum [:visa, :master_card, :american_express, :dinners, :otro ]
closing_day -> integer
payment_day -> integer 
account_id -> ingete
user_id -> integer
bank_id -> integer
total_quota -> decimal
available_quota -> decimal
handling_fee -> decimal

Validaciones
- closing_day y payment_day deben de ser valores desde 1 a 31
- account_id no puede estar en blanco
- Nombre no puede estar en blanco

**Comment by JymsD** [comment]
@DanielArenas , debo crear el modelo o ya existe?
