### ISSUE TITLE
Actualizar perfil

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#12]
Actualizar perfil del usuario, datos como primer nombre, apellido, email contraseña y la foto, esto va a funcionar en la parte superior derecha en el link de perfil

**Comment by JymsD** [comment]
Hola @DanielArenas , por favor me aclaras un poco mas este issue, se quiere es poder editar los atributos que el usuario registro?

**Comment by DanielArenas** [comment]
@JymsD Si queremos es que el usuarios pueda actualizar su informacion basica incluyendo actualizar contraseña y cambiar su foto de perfil

**Comment by DanielArenas** [comment]
@JymsD Cuando trato de actualizar algun campo de pantalla de perfil o solo agregar la foto, me pide obligatoriamente la contraseña, no deberia de ser asi
