### ISSUE TITLE
Agregar Tarjetas de credito

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#4]
Campos

user_id:integer
name:string
flag:string
limit:float
closing_day:integer
payment_day:integer

El campo flag es un enum que debe contener uno de los siguientes valores

- Visa
- Mastercard
- American Express

mirar esta documentacion de como funcionan los enum

http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html

**Comment by kamirob** [comment]
Se añadieron las tarjetas de crédito correctamente.
