### ISSUE TITLE
Agregar type_category a categoria

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#4]
Ya tenemos la tabla de tipo de categoria necesitamos asociarlo al modelo categoria, los cuales va a tener por defecto

- Empresa
- Familia
- Local
- Casa
- Auto
- Tercero

**Comment by JymsD** [comment]
@DanielArenas en el formulario de categorias, se debe agregar el type_category?

**Comment by JymsD** [comment]
Listo, ya di push y cree el pull request
