### ISSUE TITLE
Proceso al guardar Cuentas y Categoriar

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#7]
Cuando se esta creando o editando una nueva categoria, y todo salio bien se redirecciona a la pantalla de show.html.erb, vamos a cambiar esto si la categoria es nueva y se crea correctamente se redirecciona a la panalla editar.

Lo mismo para cuentas

**Comment by MIguelAU** [comment]
se cambiaron las redirecciones de categories y de accountas
