### ISSUE TITLE
Remover opcion en cuentas

### ISSUE THREAD

**Issue by DanielArenas** [DanielArenas/cashort#9]
En la pantalla de cuentas necesitamos remover la opcion 'please select', porque esto genera error mas adelante, cuando los cuentas no esta asociadas a ningun banco

**Comment by JymsD** [comment]
@DanielArenas , En este issue lo que se quiere es eliminar esa opcion 'please select', y dejar una opcion seleccionada por defecto?.

**Comment by DanielArenas** [comment]
@JymsD si, en el campo de Bank por defecto cuando el registro es nuevo dejar seleccionado 'sin banco'
